openapi: 3.1.0
info:
  title: Swagger Petstore - OpenAPI 3.1
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://exercice1.back.worldskill.local
paths:
  /breed/:
    get:
      description: Get the list of all breeds
      parameters:
        - name: size
          in: query
          schema:
            type: number
            default: 50
        - name: page
          in: query
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: List of all breeds
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
  /breed/{breed}:
    get:
      description: Get the list of sub-breed of a breed
      parameters:
        - name: breed
          in: path
          required: true
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: number
            default: 50
        - name: page
          in: query
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: List of all sub-breeds
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /breed/{breed}/images:
    get:
      description: Get all available images of a breed
      parameters:
        - name: breed
          in: path
          required: true
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: number
            default: 50
        - name: page
          in: query
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: List of all images of a breed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /breed/{breed}/images/random:
    get:
      description: Get a random image for a breed
      parameters:
        - name: breed
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response image
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

  /breed/{breed}/{subbreed}/images:
    get:
      description: Get all available images of a sub-breed
      parameters:
        - name: breed
          in: path
          required: true
          schema:
            type: string
        - name: subbreed
          in: path
          required: true
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: number
            default: 50
        - name: page
          in: query
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: List of all images of a breed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /breed/{breed}/{subbreed}/images/random:
    get:
      description: Get a random image for a sub-breed
      parameters:
        - name: breed
          in: path
          required: true
          schema:
            type: string
        - name: subbreed
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response image
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string  